using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace Mcivil
{
  public partial class Contact : System.Web.UI.Page
  {
    protected void Page_Load(object sender, EventArgs e)
    {
      System.Web.UI.HtmlControls.HtmlAnchor anchor = (System.Web.UI.HtmlControls.HtmlAnchor)this.Page.Master.FindControl("nav_contact");
      anchor.Attributes.Add("class", "active");
    }

    protected void contact_submit_Click(object sender, EventArgs e)
    {
      // send contact us email 
      string mailSubject = "[System] Contact from " + FirstNameTextBox.Text;
      string message = string.Empty;
      message += "<b>--- This email is generated by MCivil website - Contact Us page ---</b><br /><br /><br />";
      message += "<b>Client First Name:</b>  <br />" + FirstNameTextBox.Text + "<br /><br />";
      message += "<b>Client Email Address:</b>  <br />" + EmailAddressTextBox.Text + "<br /><br />";
      message += "<b>Client Message:</b>  <br />" + MessageTextBox.Text.Replace(Environment.NewLine, "<br/>") + "<br />";
      MailMessage myMessage = new MailMessage("system.mcivil@gmail.com ", "info@mcivil.co.nz", mailSubject, message);
      myMessage.IsBodyHtml = true;
      //SmtpClient mySmtpClient = new SmtpClient();
      //mySmtpClient.Send(myMessage);

      // show confirm message
      ConfirmMsg.Text = "Thanks for contacting us. We will get back to you as soon as possible.";
      PlaceHolderConfirmMsg.Visible = true;
    }
  }
}